//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentNote
    {
        public int AssignNoteID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NoteCreationDate { get; set; }
        public Nullable<int> ProjectAssignID { get; set; }
        public string NoteSubject { get; set; }
        public string NoteText { get; set; }
    
        public virtual ProjectAssignment ProjectAssignment { get; set; }
        public virtual User User { get; set; }
    }
}
