//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.AssignmentFiles = new HashSet<AssignmentFile>();
            this.IdeaFiles = new HashSet<IdeaFile>();
        }
    
        public int FileID { get; set; }
        public byte[] FileContent { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        public virtual ICollection<AssignmentFile> AssignmentFiles { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<IdeaFile> IdeaFiles { get; set; }
    }
}
