//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaMetaData
    {
        public int IdeaMetaDataId { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> NumContributorViews { get; set; }
        public Nullable<int> NumAmbassadorViews { get; set; }
        public Nullable<int> NumAdminViews { get; set; }
        public Nullable<int> NumLikes { get; set; }
        public Nullable<int> NumEdits { get; set; }
        public Nullable<int> NumAssociatedFiles { get; set; }
        public Nullable<int> EstEmployeeTimeSavingsInHours { get; set; }
        public Nullable<int> NumTimesAssigned { get; set; }
        public Nullable<int> IdeaPerformanceRating { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
