//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDBEntities : DbContext
    {
        public MainDBEntities()
            : base("name=MainDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<ProjectEdit> ProjectEdits { get; set; }
        public DbSet<ProjectAssignment> ProjectAssignments { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<AssignmentMetaData> AssignmentMetaDatas { get; set; }
        public DbSet<AssignmentNote> AssignmentNotes { get; set; }
        public DbSet<IdeaMetaData> IdeaMetaDatas { get; set; }
        public DbSet<SchoolMetaData> SchoolMetaDatas { get; set; }
        public DbSet<UserMetaData> UserMetaDatas { get; set; }
        public DbSet<AssignmentFile> AssignmentFiles { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<IdeaFile> IdeaFiles { get; set; }
        public DbSet<SchoolEdit> SchoolEdits { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<SavedProject> SavedProjects { get; set; }
        public DbSet<School> Schools { get; set; }
    }
}
