//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssignment
    {
        public ProjectAssignment()
        {
            this.AssignmentMetaDatas = new HashSet<AssignmentMetaData>();
            this.AssignmentNotes = new HashSet<AssignmentNote>();
            this.AssignmentFiles = new HashSet<AssignmentFile>();
        }
    
        public int ProjectAssignID { get; set; }
        public int ProjectID { get; set; }
        public int SchoolID { get; set; }
        public string AmbassadorNote { get; set; }
        public string MentorNote { get; set; }
        public string AdminNote { get; set; }
        public Nullable<int> HoursDedicatedToProject { get; set; }
        public string ProgressStatus { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DateInProgress { get; set; }
        public Nullable<System.DateTime> DateInterned { get; set; }
        public Nullable<System.DateTime> DateProduction { get; set; }
        public Nullable<System.DateTime> DateArchived { get; set; }
    
        public virtual ICollection<AssignmentMetaData> AssignmentMetaDatas { get; set; }
        public virtual ICollection<AssignmentNote> AssignmentNotes { get; set; }
        public virtual ICollection<AssignmentFile> AssignmentFiles { get; set; }
        public virtual Project Project { get; set; }
        public virtual School School { get; set; }
    }
}
