//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.IdeaFiles = new HashSet<IdeaFile>();
            this.IdeaMetaDatas = new HashSet<IdeaMetaData>();
            this.Notifications = new HashSet<Notification>();
            this.ProjectAssignments = new HashSet<ProjectAssignment>();
            this.ProjectEdits = new HashSet<ProjectEdit>();
            this.SavedProjects = new HashSet<SavedProject>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDesc { get; set; }
        public string BusinessJustification { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> InternDate { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string AdminNote { get; set; }
        public string ChangeControlNumber { get; set; }
    
        public virtual ICollection<IdeaFile> IdeaFiles { get; set; }
        public virtual ICollection<IdeaMetaData> IdeaMetaDatas { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<ProjectAssignment> ProjectAssignments { get; set; }
        public virtual ICollection<ProjectEdit> ProjectEdits { get; set; }
        public virtual ICollection<SavedProject> SavedProjects { get; set; }
        public virtual User User { get; set; }
    }
}
