//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedProject
    {
        public int SaveID { get; set; }
        public int ProjectID { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectBusinessJustification { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
