//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolEdit
    {
        public int SchoolEditID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Department { get; set; }
        public string Class { get; set; }
        public Nullable<decimal> StreetNumber { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual School School { get; set; }
    }
}
