//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMetaData
    {
        public int SchoolMetadataID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> NumCompletedProjects { get; set; }
        public Nullable<int> EstProvidedManHours { get; set; }
        public Nullable<int> AdminQualityRating { get; set; }
        public Nullable<int> AmbassadorQualityRating { get; set; }
        public Nullable<int> NumInternsHired { get; set; }
    
        public virtual School School { get; set; }
    }
}
