//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.ProjectAssignments = new HashSet<ProjectAssignment>();
            this.SchoolEdits = new HashSet<SchoolEdit>();
            this.SchoolMetaDatas = new HashSet<SchoolMetaData>();
        }
    
        public int SchoolID { get; set; }
        public string Username { get; set; }
        public string SchoolName { get; set; }
        public decimal Phone { get; set; }
        public string Email { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Department { get; set; }
        public string Class { get; set; }
        public decimal StreetNumber { get; set; }
        public string StreetName { get; set; }
        public int ZipCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<ProjectAssignment> ProjectAssignments { get; set; }
        public virtual ICollection<SchoolEdit> SchoolEdits { get; set; }
        public virtual ICollection<SchoolMetaData> SchoolMetaDatas { get; set; }
        public virtual User User { get; set; }
    }
}
