//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceIdeaBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Notifications = new HashSet<Notification>();
            this.ProjectEdits = new HashSet<ProjectEdit>();
            this.AssignmentNotes = new HashSet<AssignmentNote>();
            this.UserMetaDatas = new HashSet<UserMetaData>();
            this.Files = new HashSet<File>();
            this.Projects = new HashSet<Project>();
            this.SavedProjects = new HashSet<SavedProject>();
            this.Schools = new HashSet<School>();
        }
    
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public int UserRole { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<ProjectEdit> ProjectEdits { get; set; }
        public virtual ICollection<AssignmentNote> AssignmentNotes { get; set; }
        public virtual ICollection<UserMetaData> UserMetaDatas { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<SavedProject> SavedProjects { get; set; }
        public virtual ICollection<School> Schools { get; set; }
    }
}
